# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/revigo-spectra',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/revigo-spectra',
                'lib_path': 'revigo_spectra'},
  'syms': {'revigo_spectra.core': {'revigo_spectra.core.foo': ('core.html#foo', 'revigo_spectra/core.py')}}}
